apiVersion: v1
kind: Service
metadata:
  name: voice-calling
  labels:
    app: voice-calling
spec:
  selector:
    app: voice-calling
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
